# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2
loom_version=1.14-SNAPSHOT
# Mod Properties
mod_version=1.1.4-fabric-1.21.11
maven_group=online.kbpf.dg_lab
archives_base_name=DG_LAB
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.139.5+1.21.11
